# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from drone_input_msgs/DroneControlInput.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DroneControlInput(genpy.Message):
  _md5sum = "a6513e4e1c03e5976bc99005c604e739"
  _type = "drone_input_msgs/DroneControlInput"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Cyclic controls
int8 w
int8 a
int8 s
int8 d

# Pedals
int8 i
int8 j
int8 k
int8 l
"""
  __slots__ = ['w','a','s','d','i','j','k','l']
  _slot_types = ['int8','int8','int8','int8','int8','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       w,a,s,d,i,j,k,l

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DroneControlInput, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.w is None:
        self.w = 0
      if self.a is None:
        self.a = 0
      if self.s is None:
        self.s = 0
      if self.d is None:
        self.d = 0
      if self.i is None:
        self.i = 0
      if self.j is None:
        self.j = 0
      if self.k is None:
        self.k = 0
      if self.l is None:
        self.l = 0
    else:
      self.w = 0
      self.a = 0
      self.s = 0
      self.d = 0
      self.i = 0
      self.j = 0
      self.k = 0
      self.l = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8b().pack(_x.w, _x.a, _x.s, _x.d, _x.i, _x.j, _x.k, _x.l))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.w, _x.a, _x.s, _x.d, _x.i, _x.j, _x.k, _x.l,) = _get_struct_8b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8b().pack(_x.w, _x.a, _x.s, _x.d, _x.i, _x.j, _x.k, _x.l))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.w, _x.a, _x.s, _x.d, _x.i, _x.j, _x.k, _x.l,) = _get_struct_8b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8b = None
def _get_struct_8b():
    global _struct_8b
    if _struct_8b is None:
        _struct_8b = struct.Struct("<8b")
    return _struct_8b
